version: "3"
services:
  app:
    build: .
  nginx:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/srv/http"
    ports:
      - "8080:80"
    depends_on:
      - "app"
